package by.epam.barkou.controller.command;

public enum CommandName {

	SIGN_IN, SIGN_UP, ADD_BOOK, WRONG_REQUEST, UPDATE_BOOK, GET_ALL_AVAILABLE_BOOKS, SHOW_PROFILE, UPDATE_PROFILE, ADD_ADMIN_RIGHTS, SET_USER_BANNED, ORDER_BOOK, SIGN_OUT, GET_AVAILABLE_BOOK, GET_USER;

}
